<?xml version="1.0" encoding="ISO-8859-1" ?>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ page import="java.io.PrintWriter"%>
<%@ page isErrorPage = "true" %>

<%-- This file generated by Sakai App Builder --%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>ERROR</title>
</head>
<body>

Exception: <% String strException = exception.getMessage(); %><br/>
<%=strException%>
<br/>
<pre>
<%
	// now display a stack trace of the exception
	PrintWriter pw = new PrintWriter( out );
	exception.printStackTrace( pw );
%>
</pre>

</body>
</html>